### ISSUE TITLE
feat: use governance to interact with interchain account

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/interchain-accounts-demo#103]

**Comment by fadeev** [comment]
What would be the difference between a user submitting a transaction with a `MsgSubmitTx` and a governance/group doing the same?

I tried submitting from a group:

```
{
  "group_policy_address": "cosmos1afk9zr2hn2jsac63h4hm60vl9z3e5u69gndzf7c99cqge3vzwjzsfwkgpd",
  "messages": [
    {
      "@type": "/cosmos.foo.MsgSubmitTx",
      "creator": "cosmos1afk9zr2hn2jsac63h4hm60vl9z3e5u69gndzf7c99cqge3vzwjzsfwkgpd",
      "connectionId": "connection-0",
      "msg": {
        "@type": "/cosmos.bank.v1beta1.MsgSend",
        "from_address": "cosmos1rzxvxy6kxay5u2dnwcck8xdsx6hnv5w46ah74k3v6jnh0437qr9qf3fq82",
        "to_address": "cosmos18pug9mrsj70pkwvgw6vhw0v8s4ufk6frnv9kdz",
        "amount": [
          {
            "denom": "stake",
            "amount": "5"
          }
        ]
      }
    }
  ],
  "metadata": "",
  "proposers": [
    "cosmos15n7qdnrwd4rpnpk3nekk9mr6ymh3h8p0l308la"
  ]
}
```

Where `from_address` is the ICA address associated with the group policy address. It doesn't throw an error, but the `MsgSend` message is not executed on the host chain.

**Comment by crodriguezvega** [comment]
There shouldn't be any difference... Did you check [the event that is emitted after executing the message on the host](https://github.com/cosmos/ibc-go/blob/e5ec801a4925e86386a44d47921bb1ddab847c8b/modules/apps/27-interchain-accounts/host/ibc_module.go#L119) to see if there was some details there of what happened?

Did you also try to process the acknowledgement from the host on the controller? Like it is done in this repo [here](https://github.com/cosmos/interchain-accounts-demo/blob/master/x/inter-tx/ibc_module.go#L114-L146) (although it's still missing the implementation to handle the response for host chains running SDK 0.46).

**Comment by fadeev** [comment]
Thank you, @crodriguezvega!

I've subscribed with:

```
ws ws://localhost:26657/websocket

{ "jsonrpc": "2.0", "method": "subscribe", "params": ["message.module='ibc_channel'"], "id": 1 }
```

When registering an interchain account it properly emitted events on both chains. When sending a tx with a `MsgSubmitTx` from a regular account, it works and events are emitted. When I used a group with the proposal above, it didn't emit events at all.

I haven't processed the ack on the controller, but afaik it should still emit events.

**Comment by AdityaSripal** [comment]
> It doesn't throw an error, but the MsgSend message is not executed on the host chain.

It would be helpful to understand where exactly in the flow this is failing?

Does the packet even get committed on the controller chain?
Is the `MsgRecvPacket` being relayed?
If so, what is the response/events emitted?

**Comment by seantking** [comment]
@fadeev happy to hop on a call with you if that is useful. I would like to try to reproduce on my side.

Thank you for opening the issue and testing things out thus far.

**Comment by fadeev** [comment]
@seantking that'd be incredibly useful 🙏 I still can't get the hang of debugging IBC issues. You can use https://calendly.com/denis-fadeev or lmk how to schedule a call with you. Really appreciate the help!

**Comment by crodriguezvega** [comment]
Closing as this is now possible with ibc-go v6.
