### ISSUE TITLE
Error relating to API-breaking changes in ibc-go v6

### ISSUE THREAD

**Issue by mxnares** [cosmos/interchain-accounts-demo#151]
Issue: I am trying to use inter-tx go package in my own chain with ibc-go v6 but facing compilation errors due to API-breaking changes introduced by v6.

Specifically, in interchain-accounts-demo/x/inter-tx/keeper/msg_server.go, the SubmitTx function has not been updated in accordance with v6 requirements described here: https://github.com/cosmos/ibc-go/blob/main/CHANGELOG.md > API Breaking, bullet one, SerializeCosmosTx input parameter.

Thank you for your time :)

**Comment by crodriguezvega** [comment]
Hi @mxnares. This was fixed as part of [this PR](https://github.com/cosmos/interchain-accounts-demo/pull/156), therefore I am closing the issue now.
