### ISSUE TITLE
Update golang relayer test scripts

### ISSUE THREAD

**Issue by crodriguezvega** [cosmos/interchain-accounts-demo#85]
The test scripts used for testing with the golang relayer are outdated (for example, the [path json file mentions an `ibcaccount` port ID](https://github.com/cosmos/interchain-accounts/blob/master/network/relayer/interchain-acc-config/paths/test1-account-test2.json) that is not used anymore). We should update the scripts to make it work with golang relayer as well.

**Comment by tmsdkeys** [comment]
I've been doing this for my workshop for the HackAtom: https://github.com/tmsdkeys/hackatom-seoul-ws

So I can update the repo, with rly v2.0.0rc4 ICA should  now be fully supported
