### ISSUE TITLE
Update to ibc-go v3.0.0

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/interchain-accounts-demo#91]
@charleenfei just pointed me to this and I would like to import it as a demo of how to use ica in wasmd.
But it uses ibc-go v3.0.0-rc2 and that is a different version than we need.

Can you update go.mod? I assume this is easy. And ideally tag, so I can import this.

**Comment by crodriguezvega** [comment]
We have already [this PR open](https://github.com/cosmos/interchain-accounts-demo/pull/89), but hasn't been merged yet. I will take care of it asap!

**Comment by crodriguezvega** [comment]
Closed by #89
